---
# This role starts a nginx component

- name: ensure nginx config directory exists
  file:
    path: "{{ nginx.confdir }}"
    state: directory
  become: "{{ nginx.dir.become }}"

- name: copy template from local to remote in nginx config directory
  template:
    src: nginx.conf.j2
    dest: "{{ nginx.confdir }}/nginx.conf"

- name: copy cert files from local to remote in nginx config directory
  copy:
    src: "files/{{ item }}"
    dest: "{{ nginx.confdir }}"
  with_items:
        - "{{ nginx.ssl.cert }}"
        - "{{ nginx.ssl.key }}"
        - "{{ nginx.ssl.client_ca_cert }}"

- name: copy password files for cert from local to remote in nginx config directory
  copy:
    src: "files/{{ nginx.ssl.password_file }}"
    dest: "{{ nginx.confdir }}"
  when: nginx.ssl.password_enabled == true

- name: ensure nginx log directory is created with permissions
  file:
    path: "{{ whisk_logs_dir }}/nginx"
    state: directory
    mode: 0777
  become: "{{ logs.dir.become }}"

- name: "pull the nginx:{{ nginx.version }} image"
  shell: "docker pull nginx:{{ nginx.version }}"
  retries: "{{ docker.pull.retries }}"
  delay: "{{ docker.pull.delay }}"

- name: Copy over take-in-out-check-file.sh script to nginx host
  copy: src={{ openwhisk_home }}/tools/nginx/take-in-out-check-file.sh dest={{ nginx.confdir }}/take-in-out-check-file.sh mode=755

- name: Take out L7 health check file from nginx
  shell: sh {{ nginx.confdir }}/take-in-out-check-file.sh take-out nginx {{ nginx.healthcheckfile }}

- name: Sleep some time in order to switch traffic to alive node
  shell: sleep {{ nginx.sleeptime }}

- name: (re)start nginx
  docker_container:
    name: nginx
    image: nginx:{{ nginx.version }}
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    hostname: "nginx"
    volumes:
      - "{{ whisk_logs_dir }}/nginx:/logs"
      - "{{ nginx.confdir }}:/etc/nginx"
    expose:
      - 8443
    ports:
      - "{{ nginx.port.http }}:80"
      - "{{ nginx.port.api }}:443"
      - "{{ nginx.port.adminportal }}:8443"

- name: make sure nginx log has permission to create hardlink to point it
  shell: docker exec -t nginx chmod 777 /logs/nginx_access.log

- name: Take in L7 health check file to nginx
  shell: sh {{ nginx.confdir }}/take-in-out-check-file.sh take-in nginx {{ nginx.healthcheckfile }}

- name: Sleep some time in order to let lb find this nginx node
  shell: sleep {{ nginx.sleeptime }}
