# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

FROM openwhisk/action-nodejs-v8:1.6.1

RUN npm install \
request@2.79.0 \
request-promise@4.1.1
