---
# This role will install Neloagent in group 'neloagents' in the environment inventory

- import_tasks: docker_login.yml

- name: "pull the {{ docker_image_tag }} image of neloagent"
  shell: "docker pull {{ docker_registry }}{{ docker_image_prefix }}/neloagent:{{ docker_image_tag }}"
  when: docker_registry != ""

- name: ensure neloagent config directory exists
  file:
    path: "{{ neloagent.confdir }}"
    state: directory

- name: ensure lambdalog directory is created with permissions
  file:
    path: "{{ whisk_logs_dir }}/lambdalog"
    state: directory
    mode: 0777

- name: copy over create-hardlink.sh script to target hosts
  copy: src={{playbook_dir}}/roles/neloagent/files/create-hardlink.sh dest=/tmp/create-hardlink.sh mode=755

- name: create log hardlink to enable neloagent parse log from the same folder
  shell: "/tmp/create-hardlink.sh {{ whisk_logs_dir }}"

- name: copy nelo2-config.json to remote in neloagent config directory
  template:
    src: nelo2-conf.json.j2
    dest: "{{ neloagent.confdir }}/nelo2-conf.json"

- name: copy nelo2-master.json to remote in neloagent config directory
  template:
    src: nelo2-master.json.j2
    dest: "{{ neloagent.confdir }}/nelo2-master.json"

- name: (re)start neloagent
  docker_container:
    name: neloagent
    hostname: lambda-log-collector
    image: "{{ docker_registry }}{{ docker_image_prefix }}/neloagent:{{ docker_image_tag }}"
    state: started
    recreate: true
    restart_policy: "{{ docker.restart.policy }}"
    volumes:
      - "{{ whisk_logs_dir }}:{{ whisk_logs_dir }}"
      - "{{ neloagent.confdir }}:/usr/local/agent-1.7.2/conf/"
