---
# This role will install controller in group 'controllers' in the environment inventory
# In deploy mode it will deploy controllers.
# In clean mode it will remove the controller containers.

- import_tasks: deploy.yml
  when: mode == "deploy"

- import_tasks: clean.yml
  when: mode == "clean"
